int _putchar(int);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion2(int n, int sqr);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int is_prime2(int n, int i);
int is_palindrome(char *s);
int _strlen_recursion(char *s);
char *_strcpy_recursion(char *dest, char *src, int i);
int wildcmp(char *s1, char *s2);
